config/routes.rb
Rails.application.routes.draw do
  get 'hello/index'
  resources :import_books, only: %i[create]
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  enum status: { backlog: 1, reading: 2, read: 3, dropped: 4 }, _default: :backlog
end

app/models/user.rb
class User
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :username
end

app/models/worker.rb
class Worker < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
    if params[:worker].eql?('true')
      ImportsJob.set(wait: 1.second).perform_later
      redirect_to hello_index_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.all
  end
end

app/controllers/import_books_controller.rb
class ImportBooksController < ApplicationController
  def create
    ImportBooksJob.set(wait: 1.seconds).perform_later
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/hello/_counter_link.html.erb
<div id="counter_link">
  <%= link_to "Clicked in #{count.to_i} times", '#', data: { step: 1, count: count.to_i, controller: 'counter', action: 'click->counter#increment' } %>
</div>

app/views/hello/index.html.erb
<h1>Hello#index</h1>
<p>Find me in app/views/hello/index.html.erb</p>

<h4>With only stimulus</h4>


<%= render 'counter_link', count: @count %>
<%= link_to 'Trigger the worker', hello_index_path(worker: true) %>

<br>
<hr>
<div id="logs">
</div>

app/views/home/_books.html.erb
<table>
  <tr>
    <th>id</th>
    <th>Title</th>
    <th>Author</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
  <% books.each.with_index(1) do |book, index| %>
    <tr>
      <td><%= index %></td>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.status %></td>
      <td>
        <%= select_tag "status", options_for_select(Book.statuses.keys, book.status), 
                                 { data: { reflex: 'change->Book#update_status', id: book.id } } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/home/index.html.erb
<br>
<h4>Welcome to reflexing app!</h4>

<p>Lets import some books with click this <%= link_to 'link', import_books_path, method: :post %></p>

<div id="import_logs"></div>

<hr>

<div class="books">
  <%= render 'books', books: @books %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reflexing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash.any? %>
      <% flash.each do |key, val| %>
        <p><%= val %></p>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>